### PR TITLE
Ease of use

### PR DESCRIPTION
**Pull request by faddat**
## Summary of changes

Currently there are twin moons but you cannot use both of them at once and that can make users and operators sad.  To address a feeling of sadness, we now simply refer to lunc as "classicd" and its files live in ~/.classic

Migration note:

validators and other operators may need to:

```bash
cp -r ~/.terra ~/.classic
```

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by ZaradarBH** [comment]
This would  potentially force all validators to upgrade their installations when we want them to deploy a new version  of terrad. Is that really a good idea Jacob?

**Comment by inon-man** [comment]
I agree with Tobias on this. It's also not a good practice to operate two nodes in same account anyway.

**Review by ZaradarBH — COMMENTED** [review]
If we decide to go down this path I suggest that we rename the binary to "terraclassic" to keep the brand association. "Classic" might be to generic. :)

Also I think we need to update dockerfiles, makefiles and scripts if we go down this path so maybe it makes sense to prepare that as part of the PR? :)

**Comment by ZaradarBH** [comment]
We have decided on todays refinement meeting that its not really viable to do this due to the massive "change management burden", so by and large I think we should just put this PR on ice and re-open it later if the need arises organically from within the validator pillar.

**Pull request closed without merging**
