### PR TITLE
Added command in makefile to purge wasm from genesis json

### PR DESCRIPTION
**Pull request by ZaradarBH**
## Summary of changes

Added genesis tooling command to makefile that allows us to purge the wasm from genesis exports to help with https://github.com/classic-terra/classic/issues/12

## Report of required housekeeping

- [x] Github issue OR spec proposal link

----

## (FOR ADMIN) Before merging

- [x] Added appropriate labels to PR
- [x] Confirm added tests are consistent with the intended behavior of changes
- [x] Ensure all tests pass

### CODE REVIEW

**Review by edk208 — APPROVED** [review]
looks good to me

**Comment by fragwuerdig** [comment]
Do we really wanna purge the WASM? I am not feeling well with this, unfortunately. @nghuyenthevinh2000, I already asked you this, but how does your pebble changes respond to the genesis file size?

**Comment by edk208** [comment]
from my understanding , adding the purging capability at the moment is just a mechanism to allow us to test stuff with the current export as it fails to load with the wasm... not as a solution to the current bloat problem that we are in.

**Comment by inon-man** [comment]
> Do we really wanna purge the WASM? I am not feeling well with this, unfortunately. @nghuyenthevinh2000, I already asked you this, but how does your pebble changes respond to the genesis file size?

It's a command you would opt to use it.

**Comment by faddat** [comment]
I'm totally okay with having this purge wasm functionality. 

I'm not okay with using it on mainnet :). 

Smashing the green button.

**Review by faddat — APPROVED** [review]

**Pull request merged**
