### PR TITLE
Tax rate

### PR DESCRIPTION
**Pull request by vuong177**
## Summary of changes
- Follow https://github.com/classic-terra/classic/pull/4, add `burn_split_param` in the treasury param table.
- Add an upgrade hander for the next release

<Describe summary of major changes here>

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
can you use this upgrade handler, in it, I have fixed the version map problem: https://github.com/classic-terra/classic/pull/28

**Comment by ZaradarBH** [comment]
The code looks good, but it looks like you forgot to update the following test as its still expecting the old keeper "schema": x/treasury/legacy/v05/migrate_test.go:185 == your missing the burn_split_param in your expected json value :)

**Comment by fragwuerdig** [comment]
Doesn't make this the split ratio modifiable via governance proposals? Is that the intention @ZaradarBH?

**Comment by ZaradarBH** [comment]
That was the idea that @vuong177 proposed. As such this is v2 of the code so will split it in two and deploy a hardcoded variant in the next release and then later one with a configurable param once we are ready to do a chain upgrade as we need to set a value in the KVStore for the TreasuryKeeper via an upgrade handler :)

**Comment by vuong177** [comment]
This PR is ready, but I think should add this to v2.0.4.

**Comment by ZaradarBH** [comment]
Ed created this branch for the 1.0.5 release @ https://github.com/classic-terra/classic/tree/v1.0.5-upgrade so I will merge this PR now :)

**Review by ZaradarBH — APPROVED** [review]

**Pull request merged**
